#index:
#    path: /
#    controller: App\Controller\DefaultController::index

gestion_atelier:
     path: /gestion/atelier
     controller: App\Controller\GestionAtelierController::index


atelier_consulter:
     path: /atelier/consulter
     controller: App\Controller\GestionAtelierController::consulter